version: "3.3"
services: 
  nginx:
    image: nginx
    container_name: nginx
  frontend:
    build:
      dockerfile: ./dockers/Dockerfile.frontend
      context: ./
    container_name: climbinvest-frontend
  backend:
    build: 
      dockerfile: ./dockers/Dockerfile.web
      context: ./
    container_name: climbinvest-backend
    env_file:
      - ./backend/.env
  postgres:
    image: "postgres"
    container_name: "postgres-db"
    ports:
      - "5432:5432"
    volumes: 
      - /usr/local/var/postgres/base
    env_file: 
      - ./backend/.env
