FROM node:12-alpine as builder

WORKDIR /app
COPY frontend/package.json .

RUN npm install
COPY frontend/. .

RUN npm run builder

FROM nginx 

EXPOSE 3000

COPY frontend/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY – from=builder /app/build /usr/share/nginx/html/
